version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.12.1
    steps:
      - checkout
      - run: python -m pipx install poetry
      - run: poetry install
      - run: poetry run pytest ./
workflows:
  main:
    jobs:
      - build
