version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.12.1
    steps:
      - checkout
      - run: python -m pip install -r requirements.txt
      - run: python -m pytest ./
workflows:
  main:
    jobs:
      - build
