version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.12.1
    steps:
      - checkout
      - run: poetry install
      - run: poetry run pytest ./
workflows:
  main:
    jobs:
      - build_and_test
